fix crash
CogentRedTester/mpv-coverart pull request #3
Opened 2020-08-20 13:44 UTC by po5

Had this happen on an icecast stream
```
[coverart] 
[coverart] stack traceback:                                                                                                                                                                                       
[coverart]      [string "/home/eva/.config/mpv/scripts/coverart.lua"]:348: in function 'main'
[coverart]      [string "/home/eva/.config/mpv/scripts/coverart.lua"]:337: in function 'fn'
[coverart]      mp.defaults:574: in function 'handler'
[coverart]      mp.defaults:495: in function 'call_event_handlers'
[coverart]      mp.defaults:529: in function 'dispatch_events'
[coverart]      mp.defaults:488: in function <mp.defaults:487>
[coverart]      [C]: in ?
[coverart]      [C]: in ?
[coverart] Lua error: [string "/home/eva/.config/mpv/scripts/coverart.lua"]:348: attempt to compare number with boolean
client removed during hook handling
```

`if not o.load_extra_files and succeeded > 0 then return end`
`succeeded` is assigned to `addFromDirectory(directory)` but that function can return `false`.

2020-08-20 14:10 UTC, CogentRedTester commented
Good catch, but why have you done `or 0 > 0` I believe it should be `and succeeded > 0`

2020-08-20 16:45 UTC, po5 commented
You already do `and succeeded > 0` and as the error says you can't compare a number with a boolean.
`succeeded or 0` returns 0 when `succeeded` is `false` to prevent this.

2020-08-21 12:14 UTC, CogentRedTester requested changes

2020-08-21 12:14 UTC, CogentRedTester commented on coverart.lua
> +        if not o.load_extra_files and succeeded or 0 > 0 then return end
`succeeded or 0 > 0` returns true when either succeeded is true, or when `0 > 0`. Since 0 can never be greater than zero this does not make any sense to include.

2020-08-21 12:14 UTC, CogentRedTester commented on coverart.lua
> +        if not o.load_extra_files and succeeded or 0 > 0 then return end
However if you make this `succeeded and succeeded > 0` then, due to how lua evaluates expressions, the second statement will only be evaluated when succeeded evaluates to true. Since succeeded will never have any values other than false, 0, or 1, this will never cause the crash, because for succeeded to evaluate to true it must be a number.

2020-08-21 12:24 UTC, CogentRedTester commented
I've actually come up with a much nicer fix for this. I'll be pushing it to master soon. Thanks for letting me know about this.

2020-08-21 12:29 UTC, CogentRedTester commented
Fixed in: bbd19aa96fea0942a3250ec38668dabf0681c818

2020-08-21 12:29 UTC, closed without merging

2020-08-21 13:34 UTC, po5 commented on coverart.lua
> +        if not o.load_extra_files and succeeded or 0 > 0 then return end
Yes I forgot parentheses around this, `(succeeded or 0) > 0` works perfectly fine.